export enum TipoArticulo {
  ACCESORIOS = 'ACCESORIOS',
  CAMISETAS = 'CAMISETAS',
  GORRAS = 'GORRAS',
  VESTIDOS = 'VESTIDOS',
  SUDADERAS = 'SUDADERAS',
  ZAPATOS = 'ZAPATOS',
  CHAQUETAS = 'CHAQUETAS',
  FALDAS = 'FALDAS',
  TODOS = 'TODOS',
}
